### ISSUE TITLE
ошибка 

### ISSUE THREAD

**Issue by CiL2951** [Fequme/Economy-bot-discord-v2#11]
Traceback (most recent call last):
  File "C:\Users\cilov\AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 740, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cilov\Desktop\Economy-bot-discord-v2-main\cogs\delete.py", line 6, in <module>
    from captcha.image import ImageCaptcha
ModuleNotFoundError: No module named 'captcha'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cilov\Desktop\Economy-bot-discord-v2-main\bot.py", line 66, in <module>
    bot.load_extension(f"cogs.{filename[:-3]}")
  File "C:\Users\cilov\AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 862, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "C:\Users\cilov\AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 743, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.delete' raised an error: ModuleNotFoundError: No module named 'captcha'

**Comment by reques6e** [comment]
```
ModuleNotFoundError: No module named 'captcha'
```

Прочитайте
