### ISSUE TITLE
Ку что за ошибка?

### ISSUE THREAD

**Issue by zakatik1337** [Fequme/Economy-bot-discord-v2#4]
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python312\Lib\site-packages\nextcord\ext\commands\bot.py", line 740, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Downloads\Economy-bot-discord-v2-main\cogs\delete.py", line 4, in <module>
    from nextcord.ext import application_checks, commands, menus
ImportError: cannot import name 'menus' from 'nextcord.ext' (unknown location)

Traceback (most recent call last):
  File "Downloads\Economy-bot-discord-v2-main\bot.py", line 66, in <module>
    bot.load_extension(f"cogs.{filename[:-3]}")
  File "AppData\Local\Programs\Python\Python312\Lib\site-packages\nextcord\ext\commands\bot.py", line 862, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "AppData\Local\Programs\Python\Python312\Lib\site-packages\nextcord\ext\commands\bot.py", line 743, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.delete' raised an error: ImportError: cannot import name 'menus' from 'nextcord.ext' (unknown location)

**Comment by zakatik1337** [comment]
Фиксани бота, не хочет запускаться вообще

**Comment by amketamin** [comment]
pip install -U nextcord-ext-menus

попробуй

**Comment by zakatik1337** [comment]
> pip install -U nextcord-ext-menus
> 
> попробуй

пробывал не воркает

**Comment by zakatik1337** [comment]
> pip install -U nextcord-ext-menus
> 
> попробуй

Так щяс это пропало теперь пишет, ModuleNotFoundError: No module named 'cooldowns' не знаешь как это установить?

**Comment by Fequme** [comment]
> > pip install -U nextcord-ext-menus
> > попробуй
> 
> Так щяс это пропало теперь пишет, ModuleNotFoundError: No module named 'cooldowns' не знаешь как это установить?

pip install function-cooldowns

**Comment by zakatik1337** [comment]
Все зароботало но теперь я пытаюсь изменить валюту пишет эту ошибку Ignoring exception in view <moduleeconomy timeout=60 children=6> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='Изменить валюту' emoji=None row=None>:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/nextcord/ui/view.py", line 375, in _scheduled_task
    await item.callback(interaction)
  File "/home/container/cogs/settings.py", line 209, in currency
    id1 = int(s1)
ValueError: invalid literal for int() with base 10: '<:heart:1098669132708315237>'

**Comment by zakatik1337** [comment]
а все понял

**Comment by zakatik1337** [comment]
но вот теперь точно ошибка при команде /shop Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x7fb86dbb2170>:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/nextcord/application_command.py", line 918, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "/home/container/cogs/shop.py", line 290, in shop
    await inter.send(embed = pages[0], view = view)
  File "/home/container/.local/lib/python3.10/site-packages/nextcord/interactions.py", line 540, in send
    return await self.response.send_message(
  File "/home/container/.local/lib/python3.10/site-packages/nextcord/interactions.py", line 896, in send_message
    await adapter.create_interaction_response(
  File "/home/container/.local/lib/python3.10/site-packages/nextcord/webhook/async_.py", line 197, in request
    raise HTTPException(response, data)
nextcord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.components.2.components.0.emoji.id: Invalid emoji
In data.components.2.components.1.emoji.id: Invalid emoji
In data.components.2.components.2.emoji.id: Invalid emoji
The above exception was the direct cause of the following exception:
nextcord.errors.ApplicationInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.components.2.components.0.emoji.id: Invalid emoji
In data.components.2.components.1.emoji.id: Invalid emoji
In data.components.2.components.2.emoji.id: Invalid emoji

**Comment by zakatik1337** [comment]
File "/home/container/cogs/shop.py", line 43, in callback
    ec.execute("UPDATE balance SET bal = bal + {} WHERE id = {}".format(math.floor(cost*0.3), people.id))
AttributeError: 'NoneType' object has no attribute 'id'
при покупке роли

**Comment by Fequme** [comment]
> File "/home/container/cogs/shop.py", line 43, in callback ec.execute("UPDATE balance SET bal = bal + {} WHERE id = {}".format(math.floor(cost*0.3), people.id)) AttributeError: 'NoneType' object has no attribute 'id' при покупке роли

в бд не нашло человека который выставил роль на продажу, по этому выдаёт ошибку что нету такого

**Comment by zakatik1337** [comment]
> > File "/home/container/cogs/shop.py", line 43, in callback ec.execute("UPDATE balance SET bal = bal + {} WHERE id = {}".format(math.floor(cost*0.3), people.id)) AttributeError: 'NoneType' object has no attribute 'id' при покупке роли
> 
> в бд не нашло человека который выставил роль на продажу, по этому выдаёт ошибку что нету такого

а что сделать надо?

**Comment by zakatik1337** [comment]
И вот ещё какой-то прикол в консоль сыпит что-то не пойму от чего это  await self(interaction, *args, **kwargs)
  File "/home/container/cogs/profilev2.py", line 671, in profile
    await interaction.response.defer()
  File "/home/container/.local/lib/python3.10/site-packages/nextcord/interactions.py", line 663, in defer
    raise InteractionResponded(self._parent)
nextcord.errors.InteractionResponded: This interaction has already been responded to before
The above exception was the direct cause of the following exception:
nextcord.errors.ApplicationInvokeError: Command raised an exception: InteractionResponded: This interaction has already been responded to before честно

**Comment by Rejes666** [comment]
> File "/home/container/cogs/shop.py", line 43, in callback ec.execute("UPDATE balance SET bal = bal + {} WHERE id = {}".format(math.floor(cost*0.3), people.id)) AttributeError: 'NoneType' object has no attribute 'id' при покупке роли

поменяй в 35 строке SELECT id на SELECT owner, а в 43 я вместо people.id поставил people_id, все работает

**Comment by Rejes666** [comment]
как с тобой можно связаться? по немногу доделываю код, ошибки там всякие фикшу, хотел бы тебе скидывать чтоб обновлялся репозиторий

**Comment by Fequme** [comment]
> как с тобой можно связаться? по немногу доделываю код, ошибки там всякие фикшу, хотел бы тебе скидывать чтоб обновлялся репозиторий

Telegram: @gitfequme

**Comment by defensderts** [comment]
Loop успешно были подключены
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x000001DF4F351CD0>:
Traceback (most recent call last):
  File "D:\Users\Админ\Desktop\Economy-bot-discord-v2-main\cogs\clan.py", line 787, in clan
    a = await clan_owner(back, str(owner.display_avatar.url), dopclan[3], dopclan[4], dopclan[11], voicetime, dopclan[12], dopclan[6], dopclan[13], dopclan[14])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Админ\Desktop\Economy-bot-discord-v2-main\clan.py", line 38, in clan_owner
    awa_clan = Image.open(io.BytesIO(awa_clan)).resize((310,310))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Админ\python\Lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001DF575B6700>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Админ\python\Lib\site-packages\nextcord\application_command.py", line 918, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "D:\Users\Админ\Desktop\Economy-bot-discord-v2-main\cogs\clan.py", line 800, in clan
    except Error as e:
           ^^^^^
NameError: name 'Error' is not defined

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: NameError: name 'Error' is not defined



в чем проблема?

**Comment by CiL2951** [comment]
C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\health_check.py:25: DistributionWarning: discord.py is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord.py`
  warn(message, DistributionWarning, stacklevel=0)
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 740, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Desktop\Economy-bot-discord-v2-main\cogs\delete.py", line 4, in <module>
    from nextcord.ext import application_checks, commands, menus
ImportError: cannot import name 'menus' from 'nextcord.ext' (unknown location)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Desktop\Economy-bot-discord-v2-main\bot.py", line 66, in <module>
    bot.load_extension(f"cogs.{filename[:-3]}")
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 862, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 743, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.delete' raised an error: ImportError: cannot import name 'menus' from 'nextcord.ext' (unknown location)

**Comment by CiL2951** [comment]
"AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\health_check.py:25: DistributionWarning: discord.py is installed which is incompatible with nextcord. Please remove this library by using `pip3 uninstall discord.py`
  warn(message, DistributionWarning, stacklevel=0)
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 740, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Desktop\Economy-bot-discord-v2-main\cogs\delete.py", line 4, in <module>
    from nextcord.ext import application_checks, commands, menus
ImportError: cannot import name 'menus' from 'nextcord.ext' (unknown location)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Desktop\Economy-bot-discord-v2-main\bot.py", line 66, in <module>
    bot.load_extension(f"cogs.{filename[:-3]}")
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 862, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 743, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.delete' raised an error: ImportError: cannot import name 'menus' from 'nextcord.ext' (unknown location)

**Comment by CiL2951** [comment]
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 740, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Desktop\Economy-bot-discord-v2-main\cogs\delete.py", line 6, in <module>
    from captcha.image import ImageCaptcha
ModuleNotFoundError: No module named 'captcha'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Desktop\Economy-bot-discord-v2-main\bot.py", line 66, in <module>
    bot.load_extension(f"cogs.{filename[:-3]}")
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 862, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 743, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.delete' raised an error: ModuleNotFoundError: No module named 'captcha'

**Comment by CiL2951** [comment]
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 740, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Desktop\Economy-bot-discord-v2-main\cogs\delete.py", line 6, in <module>
    from captcha.image import ImageCaptcha
ModuleNotFoundError: No module named 'captcha'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cilov\Desktop\Economy-bot-discord-v2-main\bot.py", line 66, in <module>
    bot.load_extension(f"cogs.{filename[:-3]}")
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 862, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\nextcord\ext\commands\bot.py", line 743, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.delete' raised an error: ModuleNotFoundError: No module named 'captcha'

**Comment by reques6e** [comment]
> > >

не использовать этот код
