### ISSUE TITLE
ошибочка

### ISSUE THREAD

**Issue by defencebomb** [Fequme/Economy-bot-discord-v2#5]
помогите пожалуйста 
Traceback (most recent call last):
  File "/storage/emulated/0/Download/eco/bot.py", line 2, in <module>
    import nextcord
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nextcord/__init__.py", line 42, in <module>
    from .health_check import *
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nextcord/health_check.py", line 3, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by Crone720** [comment]
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by Fequme** [comment]
pip install -U setuptools

**Comment by defencebomb** [comment]
> pip install -U setuptools

теперь это Traceback (most recent call last):
  File "/storage/emulated/0/Download/eco/bot.py", line 64, in <module>
    for filename in os.listdir(".\cogs"):
                    ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.\\cogs'

**Comment by defencebomb** [comment]
теперь это Traceback (most recent call last):
File "/storage/emulated/0/Download/eco/bot.py", line 64, in
for filename in os.listdir(".\cogs"):
^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.\cogs'

**Comment by Fequme** [comment]
зайди в [bot.py](https://github.com/Fequme/Economy-bot-discord-v2/blob/main/bot.py) и поменяй "./cogs" на "cogs", может помочь

**Comment by defencebomb** [comment]
теперь это Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 740, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/storage/emulated/0/Download/eco/cogs/delete.py", line 6, in <module>
    from captcha.image import ImageCaptcha
ModuleNotFoundError: No module named 'captcha'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/emulated/0/Download/eco/bot.py", line 66, in <module>
    bot.load_extension(f"cogs.{filename[:-3]}")
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 743, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.delete' raised an error: ModuleNotFoundError: No module named 'captcha'

**Comment by defencebomb** [comment]
все установил

**Comment by defencebomb** [comment]
pandas баганый не хочет скачиваться
